name: Suggestions
description: Suggest an idea for this project
title: '[SUGGESTION]:'
labels: enhancement
body:
  - type: markdown
    attributes:
        value: |
          Thanks for taking the time to fill out this suggestion!
  - type: textarea
    id: context
    attributes:
      label: Context
      description: A clear and concise description of the context of the suggestion.
      placeholder: |
        I think that X should be added to the project because Y.
    validations:
      required: true
  - type: textarea
    id: extra-information
    attributes:
      label: Extra information
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        ...
